[tox]
requires = tox-uv>=1.28.0
env_list = ruff, mypy, py
isolated_build = true

[testenv]
description = run pytest
extras = dev
commands =
    pytest

[testenv:ruff]
description = run ruff
extras = dev
commands =
    ruff check .
    ruff format --check .

[testenv:mypy]
description = run mypy
extras = dev
commands =
    mypy
